name: Deploy Staging Application to Server

on:
  push:
    branches: [staging]

jobs:
  build-and-deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: SSH Deploy Application
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.GH_SERVER_HOST }}
          username: ${{ secrets.GH_SERVER_USER }}
          key: ${{ secrets.GH_SERVER_SSH_KEY }}
          port: ${{ secrets.GH_SERVER_PORT }}
          script: |
            cd ${{ secrets.GH_SERVER_PATH }}
            git fetch origin
            git checkout staging
            git pull origin staging
            php artisan optimize:clear
            composer install --no-interaction --prefer-dist --optimize-autoloader
            php artisan migrate --force
            chmod +x ./deploy/expect/shield-generate.sh
            ./deploy/expect/shield-generate.sh
            php artisan filament:optimize
            php artisan config:cache
            php artisan route:cache
            php artisan view:cache
            php artisan event:cache
            cp ./deploy/supervisor/${{ secrets.GH_SERVER_SUPERVISOR_PREFIX }}-queue.conf /etc/supervisor/conf.d/
            cp ./deploy/supervisor/${{ secrets.GH_SERVER_SUPERVISOR_PREFIX }}-schedule.conf /etc/supervisor/conf.d/
            sudo supervisorctl reread
            sudo supervisorctl update
            sudo supervisorctl restart ${{ secrets.GH_SERVER_SUPERVISOR_PREFIX }}-queue
            sudo supervisorctl restart ${{ secrets.GH_SERVER_SUPERVISOR_PREFIX }}-schedule
