name: Deploy Laravel Application to Server

on:
  push:
    branches: [main]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: SSH Pull Latest Code
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.GH_SERVER_HOST }}
          username: ${{ secrets.GH_SERVER_USER }}
          key: ${{ secrets.GH_SERVER_SSH_KEY }}
          port: ${{ secrets.GH_SERVER_PORT }}
          script: |
            cd ${{ secrets.GH_SERVER_PATH }}
            git pull origin main

      - name: SSH Composer Install
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.GH_SERVER_HOST }}
          username: ${{ secrets.GH_SERVER_USER }}
          key: ${{ secrets.GH_SERVER_SSH_KEY }}
          port: ${{ secrets.GH_SERVER_PORT }}
          script: |
            cd ${{ secrets.GH_SERVER_PATH }}
            composer install --no-interaction --prefer-dist --optimize-autoloader
      
      - name: SSH Artisan Migrate
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.GH_SERVER_HOST }}
          username: ${{ secrets.GH_SERVER_USER }}
          key: ${{ secrets.GH_SERVER_SSH_KEY }}
          port: ${{ secrets.GH_SERVER_PORT }}
          script: |
            cd ${{ secrets.GH_SERVER_PATH }}
            php artisan migrate --force

      - name: SSH Artisan Optimize
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.GH_SERVER_HOST }}
          username: ${{ secrets.GH_SERVER_USER }}
          key: ${{ secrets.GH_SERVER_SSH_KEY }}
          port: ${{ secrets.GH_SERVER_PORT }}
          script: |
            cd ${{ secrets.GH_SERVER_PATH }}
            php artisan optimize:clear
            php artisan filament:optimize
            php artisan config:cache
            php artisan route:cache
            php artisan view:cache
            php artisan event:cache
    
      - name: SSH Restart Artisan Workers
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.GH_SERVER_HOST }}
          username: ${{ secrets.GH_SERVER_USER }}
          key: ${{ secrets.GH_SERVER_SSH_KEY }}
          port: ${{ secrets.GH_SERVER_PORT }}
          script: |
            cd ${{ secrets.GH_SERVER_PATH }}
            sh ./app/CronJob/queue.sh
            sh ./app/CronJob/schedule.sh
